/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Defaultfeedrate = number;
export type Terminal = boolean;
export type Windtype = "hoop";
export type Frictionlambda = number;
export type Leadinmm = number;
export type Leadoutdegrees = number;
export type Lockdegrees = number;
export type Patternnumber = number;
export type Skipindex = number;
export type Skipinitialnearlock = boolean;
export type Windangle = number;
export type Windtype1 = "helical";
export type Mandrelrotation = number;
export type Windtype2 = "skip";
export type Layers = (HoopLayer | HelicalLayer | SkipLayer)[];
export type Diameter = number;
export type Enddiameter = number | null;
export type Type = "vonKarman";
export type Windlength = number;
/**
 * Version of the .wind file format schema (1.x).
 */
export type SchemaVersion = string;
export type Thickness = number;
export type Width = number;

/**
 * Schema for FiberPath filament winding pattern definitions
 */
export interface WindDefinition {
  defaultFeedRate: Defaultfeedrate;
  layers: Layers;
  mandrelParameters: MandrelParameters;
  schemaVersion?: SchemaVersion;
  towParameters: TowParameters;
  [k: string]: unknown;
}
export interface HoopLayer {
  terminal?: Terminal;
  windType?: Windtype;
  [k: string]: unknown;
}
export interface HelicalLayer {
  frictionLambda?: Frictionlambda;
  leadInMM: Leadinmm;
  leadOutDegrees: Leadoutdegrees;
  lockDegrees: Lockdegrees;
  patternNumber: Patternnumber;
  skipIndex: Skipindex;
  skipInitialNearLock?: Skipinitialnearlock;
  windAngle: Windangle;
  windType?: Windtype1;
  [k: string]: unknown;
}
export interface SkipLayer {
  mandrelRotation: Mandrelrotation;
  windType?: Windtype2;
  [k: string]: unknown;
}
export interface MandrelParameters {
  diameter: Diameter;
  endDiameter?: Enddiameter;
  profile?: VonKarmanProfile | null;
  windLength: Windlength;
  [k: string]: unknown;
}
/**
 * Von Kármán (LD-Haack) nose profile (schemaVersion 1.2+).
 *
 * A non-developable surface of revolution: radius runs from the mandrel
 * ``diameter`` at the base (z=0) to 0 at the tip (z=``windLength``). The profile
 * carries only its ``type`` discriminator — base radius comes from ``diameter`` and
 * axial length from ``windLength`` (no duplicated dimensions), mirroring how
 * ``endDiameter`` reuses those fields. ``type`` lets other profiles (domes) be added
 * additively later.
 */
export interface VonKarmanProfile {
  type: Type;
  [k: string]: unknown;
}
export interface TowParameters {
  thickness: Thickness;
  width: Width;
  [k: string]: unknown;
}
