/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe the sidecar supervisor polls for readiness.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Plan
         * @description Plan a wind from an in-memory definition and return the G-code program.
         */
        post: operations["plan_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Plot
         * @description Render an unwrapped 2D preview of a G-code program as a PNG.
         */
        post: operations["plot_plot_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulate */
        post: operations["simulate_simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate
         * @description Validate a wind definition.
         *
         *     The body is schema-checked by pydantic (malformed -> 422). A full plan run
         *     surfaces semantic errors (e.g. out-of-range wind angle) as PlanningError,
         *     which the app maps to 400.
         */
        post: operations["validate_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ApiError
         * @description Error envelope returned for 4xx responses (``{"detail": "..."}``).
         */
        ApiError: {
            /** Detail */
            detail: string;
        };
        /** GcodeRequest */
        GcodeRequest: {
            /**
             * Gcode
             * @description G-code program to process, newline separated.
             */
            gcode: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HelicalLayer */
        HelicalLayer: {
            /** Leadinmm */
            leadInMM: number;
            /** Leadoutdegrees */
            leadOutDegrees: number;
            /** Lockdegrees */
            lockDegrees: number;
            /** Patternnumber */
            patternNumber: number;
            /** Skipindex */
            skipIndex: number;
            /**
             * Skipinitialnearlock
             * @default false
             */
            skipInitialNearLock: boolean;
            /** Windangle */
            windAngle: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            windType: "helical";
        };
        /** HoopLayer */
        HoopLayer: {
            /**
             * Terminal
             * @default false
             */
            terminal: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            windType: "hoop";
        };
        /** MandrelParameters */
        MandrelParameters: {
            /** Diameter */
            diameter: number;
            /** Windlength */
            windLength: number;
        };
        /** PlanLayerOut */
        PlanLayerOut: {
            /** Commandcount */
            commandCount: number;
            /** Cumulativetimeseconds */
            cumulativeTimeSeconds: number;
            /** Cumulativetowmeters */
            cumulativeTowMeters: number;
            /** Index */
            index: number;
            /** Terminal */
            terminal: boolean;
            /** Timeseconds */
            timeSeconds: number;
            /** Towmeters */
            towMeters: number;
            /** Windtype */
            windType: string;
        };
        /** PlanResultOut */
        PlanResultOut: {
            /** Commandcount */
            commandCount: number;
            /** Gcode */
            gcode: string;
            /** Layers */
            layers: components["schemas"]["PlanLayerOut"][];
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: "1.0";
            /** Timeseconds */
            timeSeconds: number;
            /** Towmeters */
            towMeters: number;
        };
        /** SimulationResultOut */
        SimulationResultOut: {
            /** Averagefeedratemmpm */
            averageFeedRateMmpm: number;
            /** Commandsexecuted */
            commandsExecuted: number;
            /** Estimatedtimeseconds */
            estimatedTimeSeconds: number;
            /** Moves */
            moves: number;
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: "1.0";
            /** Totaldistancemm */
            totalDistanceMm: number;
            /** Towlengthmm */
            towLengthMm: number;
        };
        /** SkipLayer */
        SkipLayer: {
            /** Mandrelrotation */
            mandrelRotation: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            windType: "skip";
        };
        /** TowParameters */
        TowParameters: {
            /** Thickness */
            thickness: number;
            /** Width */
            width: number;
        };
        /** ValidateResponse */
        ValidateResponse: {
            /** Valid */
            valid: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WindDefinition */
        WindDefinition: {
            /** Defaultfeedrate */
            defaultFeedRate: number;
            /** Layers */
            layers: (components["schemas"]["HoopLayer"] | components["schemas"]["HelicalLayer"] | components["schemas"]["SkipLayer"])[];
            mandrelParameters: components["schemas"]["MandrelParameters"];
            /**
             * Schema Version
             * @description Version of the .wind file format schema (1.x).
             * @default 1.0
             */
            schemaVersion: string;
            towParameters: components["schemas"]["TowParameters"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    plan_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WindDefinition"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResultOut"];
                };
            };
            /** @description Input rejected by the compute engine. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plot_plot_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GcodeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "image/png": unknown;
                };
            };
            /** @description Input rejected by the compute engine. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GcodeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationResultOut"];
                };
            };
            /** @description Input rejected by the compute engine. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WindDefinition"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateResponse"];
                };
            };
            /** @description Input rejected by the compute engine. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
