/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe the sidecar supervisor polls for readiness.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/machine/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Command
         * @description Run a single manual G-code command (rejected 409 while a job streams).
         */
        post: operations["send_command_machine_commands_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/machine/connection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Connect
         * @description Open the serial port and return the controller's connection banner.
         */
        post: operations["connect_machine_connection_post"];
        /**
         * Disconnect
         * @description Cancel any active job and close the serial port.
         */
        delete: operations["disconnect_machine_connection_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/machine/estop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Emergency Stop
         * @description Issue #196 safety stop: write M112 out-of-band, bypassing the lock.
         */
        post: operations["emergency_stop_machine_estop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/machine/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Job
         * @description Start streaming a G-code program on a background worker.
         */
        post: operations["start_job_machine_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/machine/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job
         * @description Poll a job's status and the event log entries with ``seq > since``.
         */
        get: operations["get_job_machine_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/machine/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Job
         * @description Stop a job gracefully; the connection stays open.
         */
        post: operations["cancel_job_machine_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/machine/jobs/{job_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pause Job
         * @description Pause a streaming job before its next line (host-side).
         */
        post: operations["pause_job_machine_jobs__job_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/machine/jobs/{job_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume Job
         * @description Resume a paused job.
         */
        post: operations["resume_job_machine_jobs__job_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/machine/ports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Ports
         * @description Enumerate the serial ports available on the host.
         */
        get: operations["list_ports_machine_ports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Plan
         * @description Plan a wind from an in-memory definition and return the G-code program.
         */
        post: operations["plan_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Plot
         * @description Render an unwrapped 2D preview of a G-code program as a PNG.
         */
        post: operations["plot_plot_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulate */
        post: operations["simulate_simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate
         * @description Validate a wind definition.
         *
         *     The body is schema-checked by pydantic (malformed -> 422). A full plan run
         *     surfaces semantic errors (e.g. out-of-range wind angle) as PlanningError,
         *     which the app maps to 400.
         */
        post: operations["validate_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ApiError
         * @description Error envelope returned for 4xx responses (``{"detail": "..."}``).
         */
        ApiError: {
            /** Detail */
            detail: string;
        };
        /** CommandRequest */
        CommandRequest: {
            /**
             * Gcode
             * @description A single G-code command to run manually.
             */
            gcode: string;
        };
        /** CommandResponse */
        CommandResponse: {
            /** Responses */
            responses: string[];
        };
        /** ConnectRequest */
        ConnectRequest: {
            /**
             * Baud Rate
             * @default 250000
             */
            baud_rate: number;
            /** Port */
            port: string;
            /**
             * Timeout
             * @default 10
             */
            timeout: number;
        };
        /**
         * ConnectionInfoOut
         * @description Connection banner for the #146 connection-info panel.
         */
        ConnectionInfoOut: {
            /** Baud Rate */
            baud_rate: number;
            /** Capabilities */
            capabilities: {
                [key: string]: boolean;
            };
            /** Firmware */
            firmware: string;
            /** Port */
            port: string;
            /** State */
            state: string;
        };
        /** GcodeRequest */
        GcodeRequest: {
            /**
             * Gcode
             * @description G-code program to process, newline separated.
             */
            gcode: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HelicalLayer */
        HelicalLayer: {
            /**
             * Frictionlambda
             * @default 0
             */
            frictionLambda: number;
            /** Leadinmm */
            leadInMM: number;
            /** Leadoutdegrees */
            leadOutDegrees: number;
            /** Lockdegrees */
            lockDegrees: number;
            /** Patternnumber */
            patternNumber: number;
            /** Skipindex */
            skipIndex: number;
            /**
             * Skipinitialnearlock
             * @default false
             */
            skipInitialNearLock: boolean;
            /** Windangle */
            windAngle: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            windType: "helical";
        };
        /** HoopLayer */
        HoopLayer: {
            /**
             * Terminal
             * @default false
             */
            terminal: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            windType: "hoop";
        };
        /**
         * JobEventOut
         * @description One entry from a job's monotonic event log.
         */
        JobEventOut: {
            /** Action */
            action?: string | null;
            /** Command */
            command?: string | null;
            /** Message */
            message?: string | null;
            /** Sent */
            sent?: number | null;
            /** Seq */
            seq: number;
            /** Total */
            total?: number | null;
            /** Type */
            type: string;
        };
        /** JobStatusOut */
        JobStatusOut: {
            /** Cursor */
            cursor: number;
            /** Error */
            error?: string | null;
            /** Events */
            events: components["schemas"]["JobEventOut"][];
            /** Id */
            id: string;
            /** Sent */
            sent: number;
            /** State */
            state: string;
            /** Total */
            total: number;
        };
        /** MandrelParameters */
        MandrelParameters: {
            /** Diameter */
            diameter: number;
            /** Enddiameter */
            endDiameter?: number | null;
            profile?: components["schemas"]["VonKarmanProfile"] | null;
            /** Windlength */
            windLength: number;
        };
        /** PlanLayerOut */
        PlanLayerOut: {
            /** Commandcount */
            commandCount: number;
            /** Cumulativetimeseconds */
            cumulativeTimeSeconds: number;
            /** Cumulativetowmeters */
            cumulativeTowMeters: number;
            /** Index */
            index: number;
            /** Terminal */
            terminal: boolean;
            /** Timeseconds */
            timeSeconds: number;
            /** Towmeters */
            towMeters: number;
            /** Windtype */
            windType: string;
        };
        /** PlanResultOut */
        PlanResultOut: {
            /** Commandcount */
            commandCount: number;
            /** Gcode */
            gcode: string;
            /** Layers */
            layers: components["schemas"]["PlanLayerOut"][];
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: "1.0";
            /** Timeseconds */
            timeSeconds: number;
            /** Towmeters */
            towMeters: number;
        };
        /**
         * PortInfoOut
         * @description One serial port discovered on the host.
         */
        PortInfoOut: {
            /** Description */
            description: string;
            /** Hwid */
            hwid: string;
            /** Port */
            port: string;
        };
        /** SimulationResultOut */
        SimulationResultOut: {
            /** Averagefeedratemmpm */
            averageFeedRateMmpm: number;
            /** Commandsexecuted */
            commandsExecuted: number;
            /** Estimatedtimeseconds */
            estimatedTimeSeconds: number;
            /** Moves */
            moves: number;
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: "1.0";
            /** Totaldistancemm */
            totalDistanceMm: number;
            /** Towlengthmm */
            towLengthMm: number;
        };
        /** SkipLayer */
        SkipLayer: {
            /** Mandrelrotation */
            mandrelRotation: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            windType: "skip";
        };
        /** StartJobRequest */
        StartJobRequest: {
            /**
             * Gcode
             * @description G-code program to stream, newline separated.
             */
            gcode: string;
        };
        /** StartJobResponse */
        StartJobResponse: {
            /** Job Id */
            job_id: string;
            /** Total */
            total: number;
        };
        /** TowParameters */
        TowParameters: {
            /** Thickness */
            thickness: number;
            /** Width */
            width: number;
        };
        /** ValidateResponse */
        ValidateResponse: {
            /** Valid */
            valid: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VonKarmanProfile
         * @description Von Kármán (LD-Haack) nose profile (schemaVersion 1.2+).
         *
         *     A non-developable surface of revolution: radius runs from the mandrel
         *     ``diameter`` at the base (z=0) to 0 at the tip (z=``windLength``). The profile
         *     carries only its ``type`` discriminator — base radius comes from ``diameter`` and
         *     axial length from ``windLength`` (no duplicated dimensions), mirroring how
         *     ``endDiameter`` reuses those fields. ``type`` lets other profiles (domes) be added
         *     additively later.
         */
        VonKarmanProfile: {
            /**
             * Type
             * @constant
             */
            type: "vonKarman";
        };
        /** WindDefinition */
        WindDefinition: {
            /** Defaultfeedrate */
            defaultFeedRate: number;
            /** Layers */
            layers: (components["schemas"]["HoopLayer"] | components["schemas"]["HelicalLayer"] | components["schemas"]["SkipLayer"])[];
            mandrelParameters: components["schemas"]["MandrelParameters"];
            /**
             * Schema Version
             * @description Version of the .wind file format schema (1.x).
             * @default 1.0
             */
            schemaVersion: string;
            towParameters: components["schemas"]["TowParameters"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    send_command_machine_commands_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommandRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            /** @description Input rejected by the compute engine. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    connect_machine_connection_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionInfoOut"];
                };
            };
            /** @description Input rejected by the compute engine. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disconnect_machine_connection_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    emergency_stop_machine_estop_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    start_job_machine_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartJobResponse"];
                };
            };
            /** @description Input rejected by the compute engine. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_machine_jobs__job_id__get: {
        parameters: {
            query?: {
                since?: number;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatusOut"];
                };
            };
            /** @description Input rejected by the compute engine. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_machine_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatusOut"];
                };
            };
            /** @description Input rejected by the compute engine. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_job_machine_jobs__job_id__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatusOut"];
                };
            };
            /** @description Input rejected by the compute engine. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_job_machine_jobs__job_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatusOut"];
                };
            };
            /** @description Input rejected by the compute engine. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ports_machine_ports_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortInfoOut"][];
                };
            };
        };
    };
    plan_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WindDefinition"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResultOut"];
                };
            };
            /** @description Input rejected by the compute engine. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plot_plot_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GcodeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "image/png": unknown;
                };
            };
            /** @description Input rejected by the compute engine. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GcodeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationResultOut"];
                };
            };
            /** @description Input rejected by the compute engine. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WindDefinition"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateResponse"];
                };
            };
            /** @description Input rejected by the compute engine. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
